/**
 * Converts the generated PA-package Markdown into a Word-compatible HTML
 * document and triggers a download. Word opens application/msword HTML as a
 * fully-formatted .doc, giving an enterprise-grade export with no dependency.
 */

const escapeHtml = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const inline = (s: string): string =>
  escapeHtml(s).replace(/\*\*([^*]+)\*\*/g, '<b>$1</b>')

/** Minimal Markdown -> HTML for the letter/package body. */
function markdownToHtml(md: string): string {
  const out: string[] = []
  let list: string[] = []
  const flush = () => {
    if (list.length) {
      out.push(`<ul>${list.map((li) => `<li>${li}</li>`).join('')}</ul>`)
      list = []
    }
  }
  for (const raw of md.split('\n')) {
    const line = raw.trimEnd()
    if (/^-{2,}\s*PAGEBREAK\s*-{2,}$/i.test(line.trim())) {
      flush()
      out.push('<div style="page-break-before:always; mso-special-character:line-break;"></div>')
    } else if (/^###\s+/.test(line)) {
      flush()
      out.push(`<h3>${inline(line.replace(/^###\s+/, ''))}</h3>`)
    } else if (/^##\s+/.test(line)) {
      flush()
      out.push(`<h2>${inline(line.replace(/^##\s+/, ''))}</h2>`)
    } else if (/^#\s+/.test(line)) {
      flush()
      out.push(`<h1>${inline(line.replace(/^#\s+/, ''))}</h1>`)
    } else if (/^[-*]\s+/.test(line)) {
      list.push(inline(line.replace(/^[-*]\s+/, '')))
    } else if (line.trim() === '') {
      flush()
    } else {
      flush()
      out.push(`<p>${inline(line)}</p>`)
    }
  }
  flush()
  return out.join('\n')
}

export function downloadPaPackageDoc(markdown: string, payerName: string, patientName: string): void {
  const bodyHtml = markdownToHtml(markdown)
  const safePayer = (payerName || 'payer').replace(/[^a-z0-9]+/gi, '-')
  const safePatient = (patientName || 'patient').replace(/[^a-z0-9]+/gi, '-')
  const generatedOn = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
  const meta = escapeHtml(
    `Payer: ${payerName || '—'}  ·  Patient: ${patientName || '—'}  ·  Generated: ${generatedOn}`,
  )

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8" />
<title>Prior Authorization Submission Package</title>
<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom><w:DoNotOptimizeForBrowser/></w:WordDocument></xml><![endif]-->
<style>
  @page { size: 8.5in 11in; margin: 0.9in 1in 1in 1in; mso-header-margin: 0.5in; mso-footer-margin: 0.5in; }
  body { font-family: 'Calibri', 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #0c0c0c; line-height: 1.5; }
  .band { border-top: 3pt solid #091121; border-bottom: 1pt solid #c1c9da; padding: 8pt 0 10pt; margin: 0 0 14pt; }
  .band-title { font-size: 15pt; font-weight: bold; color: #091121; letter-spacing: 0.4pt; }
  .band-meta { font-size: 9pt; color: #4c566f; margin-top: 3pt; }
  h1 { font-size: 15pt; color: #091121; margin: 0 0 6pt; }
  h2 { font-size: 12pt; color: #2753b3; border-bottom: 1pt solid #c1c9da; padding-bottom: 2pt; margin: 15pt 0 6pt; text-transform: uppercase; letter-spacing: 0.3pt; }
  h3 { font-size: 11.5pt; color: #091121; margin: 12pt 0 4pt; }
  p { margin: 0 0 8pt; }
  ul { margin: 0 0 10pt 0; padding-left: 20pt; }
  li { margin-bottom: 3pt; }
  b { color: #091121; }
  .foot { margin-top: 22pt; padding-top: 8pt; border-top: 1pt solid #c1c9da; font-size: 8pt; color: #6b7590; line-height: 1.4; }
  .conf { font-weight: bold; color: #8a5a00; margin-bottom: 4pt; }
</style>
</head>
<body>
<div class="band">
  <div class="band-title">PRIOR AUTHORIZATION SUBMISSION PACKAGE</div>
  <div class="band-meta">${meta}</div>
</div>
${bodyHtml}
<div class="foot">
  <div class="conf">CONFIDENTIAL — PROTECTED HEALTH INFORMATION (PHI)</div>
  <div>This document is intended solely for the named payer's prior authorization / utilization-management review and contains information protected under HIPAA. Unauthorized review, use, or disclosure is prohibited. If received in error, notify the sender and destroy all copies.</div>
  <div style="margin-top:5pt;">Generated by Grelin RCM AI — Prior Authorization Engine. Requires provider review and signature prior to submission to the payer.</div>
</div>
</body>
</html>`

  const blob = new Blob(['﻿', html], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `PA-Package-${safePayer}-${safePatient}.doc`
  a.click()
  URL.revokeObjectURL(url)
}
